name: build release binaries

# only run when tag is pushed
on:
  push:
    tags:
      - 'v*'
env:
  REGISTRY: ghcr.io
jobs:
  release-build:
    runs-on: ubuntu-latest
    container: ghcr.io/lingo-db/lingodb-py-dev:0eeb4dcaa2d7d1309171d2d4d366a17e5fc76c59
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Build
        run: |
          export PATH=/built-llvm/bin/:$PATH
          mkdir build
          cmake -G Ninja . -B build -DCMAKE_BUILD_TYPE=Release -DClang_DIR=/built-llvm/lib/cmake/clang -DArrow_DIR=/built-arrow/lib64/cmake/Arrow -DArrowCompute_DIR=/built-arrow/lib64/cmake/ArrowCompute -DENABLE_TESTS=OFF -DENABLE_BASELINE_BACKEND=True
          cmake --build build --target sql run-sql run-mlir mlir-db-opt sql-to-mlir
      - uses: actions/upload-artifact@master
        with:
          name: lingodb-cli-linux-amd64
          path: build/sql
      - uses: actions/upload-artifact@master
        with:
          name: lingodb-tools-linux-amd64
          path: |
            build/run-sql
            build/run-mlir
            build/mlir-db-opt
            build/sql-to-mlir
